### ISSUE TITLE
Flexible publishing of different kinds of artifacts

### ISSUE THREAD

**Issue by NicolasRouquette** [ohnosequences/sbt-github-release#10]
Currently, all artifacts are uploaded as application/zip: 

```
        releaseAssets.value foreach { asset =>
          release.uploadAsset(asset, "application/zip")
          val rel = asset.relativeTo(baseDirectory.value).getOrElse(asset)
          log.info(s"Asset [${rel}] is uploaded to Github")
        }
```

Instead of a list of asset files, how about using the artifact / file map (e.g. `packagedArtifacts` or `signedArtifacts`) to determine, based on the artifact, what kind of content the artifact file is?

**Comment by laughedelic** [comment]
It's a good idea, but what about those files that are not defined as artifacts? I think more flexible would be to make it a `List[(File, String)]` or a map (file with its mime type). Or more involved: define a `GithubReleaseAsset` type and provide implicit conversions from `Artifact`, `File` and `(File, String)` so that you can mix all of them when defining `releaseAssets` setting.

**Comment by NicolasRouquette** [comment]
ok, a map of File => String (mime type) sounds fine to me. I'll update the PR.

**Comment by laughedelic** [comment]
Just noticed it. I'll comment there.

**Comment by laughedelic** [comment]
Now I remember why it was set to `application/zip` (besides that I only thought about uploading `jar`s): 

Github [API documentation](https://developer.github.com/v3/repos/releases/#input-2) refers to the list of [acceptable media types](https://www.iana.org/assignments/media-types/media-types.xhtml) and there's no `application/java-archive`.

**Comment by laughedelic** [comment]
Done in #11 and #13.
