### ISSUE TITLE
sbt Resolver

### ISSUE THREAD

**Issue by setrar** [ohnosequences/sbt-github-release#33]
A client has been using ohnosequences/sbt-s3-resolver for private library management.

Client willing to move out of AWS, I have found  ohnosequences/sbt-github-release as a great replacement (i.e. putting library artifacts on private github) 

sbt-github-release  publishes as advertised. But I couldn't find any Resolver.

Is there a way to use sbt-github-release as a Resolver? Meaning, retrieving the published libraries using sbt-github-release as a Resolver like sbt-s3-resolver did.

I tried other options but couldn't find any viable Resolver solution.

https://stackoverflow.com/questions/35064892/store-dependencies-in-private-github-or-bitbucket-repo

Please help,

**Comment by laughedelic** [comment]
Hi @setrar! This is a good idea. I wanted to implement it for a while, but never had time and doubted if it's actually needed, because sbt supports dependencies on Git repos out of the box. Have you tried this: https://stackoverflow.com/a/22435562/736957?

**Comment by david-mcgillicuddy-ovo** [comment]
Hi, I'm also looking at this.

The solution where you add `dependsOn` to point to a repo is not especially suitable because it's not versioned.

I am surprised that we have this great plugin to push jar and pom files to github releases, but then nothing to pull from them. What do other people using this do, have a pipeline that then copies the artifacts elsewhere (e.g. to S3) where a different resolver gets them?

I'm currently playing around to see if I can do this with something like
```
resolvers += Resolver.url("foo").withPatterns(
    Patterns(artifactPatterns = "https://api.github.com/repos/<org>/<repo>/releases/assets/[artifact].[ext]?access_token=<token>")
)
```
just as a first step. That url works from curl. Currently having issues where it's still expecting that to be an ivy style repo instead of just getting the artifacts on their own.

**Comment by david-mcgillicuddy-ovo** [comment]
Update: According to this page: https://www.scala-sbt.org/1.0/docs/Resolvers.html#Custom
> Custom
> sbt provides an interface to the repository types available in Ivy: file, URL, SSH, and SFTP. A key feature of repositories in Ivy is using patterns to configure repositories.

Which means that I don't actually expect that it'll work due to the lack of a `ivy.xml` file. 
I suppose one possible fix might be to generate such files in the release?

Out of frustration I tried to then cheat using `ModuleID.from` like:
```libraryDependencies := "com.foo" %% my-lilb % "1.0.0" from "https://api.github.com/repos/:org/:repo/releases/assets/123?access_token=mytoken"```
But even that doesn't work because github requires the header `Accept: application/octet-stream` which I can only assume sbt doesn't use.

I even made a (horrific) little sbt plugin to get the asset-id:
```
import sbt.librarymanagement.{CrossVersion, ModuleID}
import com.softwaremill.sttp._
import io.circe._
import io.circe.parser._

object MyModuleIdUtils {
  implicit class ModuleIdExtras2(val value: ModuleID) {
    def fromGithubRelease(org: String = value.organization,
                          repo: String = value.name,
                          version: String = s"v${value.revision}",
                          accessToken: String = sys.env("GITHUB_TOKEN")
                         ): ModuleID = {
      val queryUri = uri"https://api.github.com/repos/$org/$repo/releases/tags/$version?access_token=$accessToken"
      val request = sttp.get(queryUri)
      implicit val backend = HttpURLConnectionBackend()
      val response = request.send()

      println(s"BUILD LOG: org '${value.organization}', repo: ${value.name}, version: ${value.revision}, cross version: ${value.crossVersion}")
      val jsonResponse = parse(response.unsafeBody).getOrElse(???)
      println(s"RESPONSE: $jsonResponse")

      val assetScalaVersion = value.crossVersion match {
        case _: CrossVersion.Binary => "2.12" // FIXME: not actually sure about this part
        case _ => throw new IllegalArgumentException("Non-binary versions not yet supported")
      }

      val assets = jsonResponse.\\("assets").head.asArray.get
      val rightAsset = assets.find(_.\\("name").head.asString.get == s"${value.name}_$assetScalaVersion-${value.revision}.jar").get
      val downloadUrl = rightAsset.\\("url").head.asString.get
      println(s"BUILD LOG 2: $downloadUrl")

      val queryUri2 = uri"$downloadUrl?access_token=$accessToken"
      val request2 = sttp.get(queryUri2).header("Accept", "application/octet-stream", true).followRedirects(false).send()

      println(s"BUILD LOG 3: ${request2.header("location")}")

      value.from(s"${request2.header("location").get}?access_token=$accessToken")
    }
  }
}
```
